# Solana Memecoin Trading Bot Configuration
# 参考 OpenSolBot 的配置结构

[bot]
name = "Solana Memecoin Bot"
version = "2.0.0"
debug = false
log_level = "INFO"

[wallet]
# 钱包配置
private_key = "your_wallet_private_key_here"
wallet_address = ""

[rpc]
# RPC 节点配置
endpoints = [
    "https://api.mainnet-beta.solana.com",
    "https://solana-api.projectserum.com"
]
websocket_endpoints = [
    "wss://api.mainnet-beta.solana.com",
    "wss://solana-api.projectserum.com"
]
timeout = 30
retry_count = 3

[api]
# API 配置
helius_api_base_url = "https://api.helius.xyz/v0"
helius_api_key = "your_helius_api_key_here"
shyft_api_base_url = "https://api.shyft.to"
shyft_api_key = "your_shyft_api_key_here"
jupiter_api_key = "your_jupiter_api_key_here"
raydium_api_key = "your_raydium_api_key_here"

[geyser]
# Geyser 模式配置
enabled = true
endpoint = "https://api.helius.xyz/v0"
token = "your_helius_token_here"
programs = [
    "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM",  # Raydium
    "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"   # Raydium AMM
]

[trading]
# 交易配置
max_position_size = 0.1
min_volume_24h = 1000000
min_fdv = 100000
max_slippage = 0.05
default_slippage = 0.01
max_daily_loss = 0.1
stop_loss_percentage = 0.2
take_profit_percentage = 0.5

[copy_trading]
# 跟单交易配置
enabled = true
leader_wallets = [
    "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM",
    "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU"
]
copy_ratio = 1.0
min_confidence_score = 70
max_copy_amount = 1.0

[telegram]
# Telegram Bot 配置
enabled = true
bot_token = "your_telegram_bot_token_here"
chat_id = "your_telegram_chat_id_here"
admin_chat_id = "your_admin_chat_id_here"

[twitter]
# Twitter 配置
enabled = false
bearer_token = "your_twitter_bearer_token_here"

[database]
# 数据库配置
mysql_url = "mysql+pymysql://root:root@127.0.0.1:3306/solana_trade_bot"
redis_url = "redis://127.0.0.1:6379/0"

[monitoring]
# 监控配置
enabled = true
refresh_interval = 30
alert_threshold = 0.05

[security]
# 安全配置
max_retry_attempts = 3
cooldown_period = 60
whitelist_wallets = []
blacklist_tokens = []

[logging]
# 日志配置
log_to_file = true
log_file_path = "logs/bot.log"
max_file_size = "10MB"
backup_count = 5
